### ISSUE TITLE
Keywords section of Info sidebar doesn't work on GTK3 build

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#227]
I'm using Gentoo and when I build Geeqie-1.2.2 with GTK3, info sidebar is missing the keywords section. Section name and arrow is present but the body is missing (or just hidden - seems to be 1px high as I can see a dashed line when I click "expand" arrow). I don't see a way to manually enlarge that section, thus I suspect that Geeqie miscalculates the needed size for that section. All other parts (Comment, Title, Copyright and so on) display correctly.

Reported by: tomaszg

**Comment by mowgli** [comment]
#227 is the number of SF bug. Not the one in GH.

**Comment by mowgli** [comment]
Ah, forget that. the two numbers are the same. :-D

**Comment by tomaszg7** [comment]
The bug is presumed resolved, but I just compiled the newly released 1.2.3 and I still can't access "keywords" section. In the meantime I have created a simple patch which solved it for me for the time being (still works in 1.2.3): https://bugs.gentoo.org/show_bug.cgi?id=579744

Moreover, for some time now, I can't resize any elements of UI: thumbnail bar, info sidebar and so on are frozen. It might be related to some change in GTK, I'm now running GTK 3.18.7.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Do den 14. Apr 2016 um 14:47 schrieb tomaszg7:
> The bug is presumed resolved, but I just compiled the newly released 1.2.3 and I still can't access "keywords" section. In the meantime I have created a simple patch which solved it for me for the time being (still works in 1.2.3): https://bugs.gentoo.org/show_bug.cgi?id=579744

Well, first, github only cares about master branch. And in the present
situation I do not want to keep bugs open until every stable release is
updated. Not, if it is not a security issue.

Feel free to cherry-pick the related patch from master branch or use
master and compile yourself. :-D

> Moreover, for some time now, I can't resize any elements of UI: thumbnail bar, info sidebar and so on are frozen. It might be related to some change in GTK, I'm now running GTK 3.18.7.

Yes, GTK3 did some major API changes and its support should be still
seen beta.

I use it still with gtk 2.24.30 and have not that many experiences with
GTK3. (I tested it sometimes but it seems to be ugly. But this is my own
view.)

So, if you find something above that fixed in a174e81, please open a new
bug for that.

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQGcBAEBCgAGBQJXD6IiAAoJEKZ8CrGAGfaszC8L/3JXzB5YhFvTGs2iSiFB4QUE
Zl4sUid8+9n9ikSp7Dhu+EiXkejsWhcXrnMbzTmA0XBw4PkZkdxofI/bfBPtfqxt
KikYvkB8Iykik8g2rL2Du4u5p6FiuNK8OEEpqES1U7kAE2IrCik/lalAEsqCquHZ
hA8vI2yAWV2gJ899ft7NyeGmaKY7Ld+7eH6IYTQ7aPm4J62BQso3bW6FNF0qONRT
D/+UcBhQOJ8FsPP7yAcAETst8LoeZ/o1OQ7QcyuoAenLGyZcNU8hGgJ1XWmRsZdz
+zLHiRfGdUiSUHQdZBarlQwgXvoUXyvu4ae3fF62gB6VCiyPQIoZo+Jpvdllb63l
37ib/J2bPcv29y5sdtQw/6i/Iz6YQNH3iU+wPPiznRJfMhRDqTSV05QYoY82T51X
2+T3RCjbla8EzbNDhgOioQ1xKxjmgWdkIDkv4TVp8U8zWMyOxkPll0r8QiOcTuRY
P6dJpKi6cn5sCHHxGsyPU9AKjXkhK6oSBFV2mwL+kA==
=aa+y
-----END PGP SIGNATURE-----

**Comment by tomaszg7** [comment]
Thanks, I now see that the commit you mention (and I was referring to it, not the status of the bug itself) was not included in the 1.2.3. I presumed it was, sorry for that.

I now compiled current git master and it works (also some other problems I had with 1.2.[23] were resolved there (like mirrored cr2 files and broken support for crw).

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Am Do den 14. Apr 2016 um 15:07 schrieb Tomasz Goli??ski:
> Thanks, I now see that the commit you mention (and I was referring to it, not the status of the bug itself) was not included in the 1.2.3. I presumed it was, sorry for that.
> 
> I now compiled current git master and it works (also some other problems I had with 1.2.[23] were resolved there (like mirrored cr2 files and broken support for crw).

Fine. :-)

Unfortunately I cannot tell that crw support is fixed for me. But this
seems to be a third-party-library problem.

If you have further informations, please drop me a note. (Version of
libgdk-pixbuf ...)

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXD6fVAAoJEKZ8CrGAGfasHFcL/0/cybCSBOb2Euse2J6e4IKM
f5KKitiggAnoTEm1TQh2KLJuqDk+BKydAszCI/+ANY0R0QLoxBuMSfex2jC01CyM
pkgUGaRBF0Hha5Ft4PhdFyS9FeSpZ0Q3yM+SrDYz+mUJdXiLRmJgPjmaOLJgk1gS
4achH0waQi522v9hMJt/0/QkYpzRxrw0SJSI5iEy4H4QgVPWZyha5Xx+c6r/7YnW
+Ou8cJCtNTfMHrVv8e8Z9fcwy3oCnUeuuVEL2ZKO9VOv6ELdiJTEIJo0iLbj5vet
Hqbp0VJ+LvVyz1q/hZj1gf9VtA0fbP4osIc+WHalb5OpUObjDQ4bP0as/TQOIcsh
9c53jc/pUJgLeFWaLb6w4OJyU8xwUTVSi156rFF/10ajMMO+ppprlGrxGYuhFJSB
RrkWSebB62GsazqNFpYwrYJ3f9c9Wwo3r51pJLuF0mrhZYXifOVp5QWerYXJdbD3
D4JK2I4APdFLQ6/oJTBnKCbsfM3aGrYppnh9/Y9AGQ==
=4sLP
-----END PGP SIGNATURE-----

**Comment by tomaszg7** [comment]
> Unfortunately I cannot tell that crw support is fixed for me. But this seems to be a third-party-library problem.

Did you mean that it's not fixed for you or that you can't test it due to the lack of sample files? If the latter, you can grab a sample file here: https://www.rawsamples.ch/index.php/en/canon or I can send you some. 

> If you have further informations, please drop me a note. (Version of libgdk-pixbuf ...)
gdk-pixbuf-2.32.3. Don't know what else is relevant, especially since I don't have anything to complain about now ;) 

BTW. There is quite a lot of GTK3-related deprecation warnings, but you're probably well aware of that.
