### ISSUE TITLE
zoom increment is not multiplicative

### ISSUE THREAD

**Issue by archenemies** [BestImageViewer/geeqie#521]
First of all the zoom increment is way too small by default, 0.05 on my systems.

Secondly, when I change it to something sensible, I see that the increment is being treated literally as an additive increment. For example if the increment is 1 and the current scale is 1, then zooming will change the scale to 2. But if the increment is 1 and the current scale is 10, then zooming will change the scale to 11.

Geeqie should zoom an image in or out by the same multiplicative factor each time. So for example if I set the zoom to 25%, an image will zoom from 1 to 1.25, or from 10 to 12.5. Users don't want the zoom factor to depend on the current zoom level. That makes it difficult to work with both really big and really small images.

**Comment by caclark** [comment]
Also ref #313

**Comment by caclark** [comment]
Fixed in commit f46058ba at geeqie.org

**Comment by archenemies** [comment]
Yay!

**Comment by archenemies** [comment]
I checked that the new version zooms properly, thanks again.

By the way Facebook suffers from the same bug, if you post a panoramic photo then the zooming is additive. I guess math education is going downhill.

I found the new code somewhat difficult to read. I would have expected something like: `if(increment>0) zoom *= 1+increment; else zoom /= 1-increment;`. But I don't understand the significance of a negative "zoom" value, which the code seems to be checking for.

When trying out the new version of Geeqie I found it much harder to use. Is it linking against a new GTK library? The one I currently use is the Arch package, it says version 1.3. The new version won't let me shrink the thumbnails panel to get a single column, and when I try to make it narrower the "File" menu gets shifted off the left side. I prefer the current behavior where the "File" menu stays visible but "Help" gets obscured on the right. Tried configuring with --disable-gtk3 but got a bunch of errors:

    cellrenderericon.o: In function `gqv_cell_renderer_icon_render':
    cellrenderericon.c:(.text+0xfab): undefined reference to `gtk_widget_get_style_context'
    cellrenderericon.c:(.text+0x10d7): undefined reference to `gtk_style_context_set_state'
    cellrenderericon.c:(.text+0x1323): undefined reference to `gtk_render_layout'
    cellrenderericon.c:(.text+0x1478): undefined reference to `gtk_style_context_save'
    cellrenderericon.c:(.text+0x1489): undefined reference to `gtk_style_context_set_state'

**Comment by caclark** [comment]
> I would have expected something like: if(increment>0) zoom *= 1+increment; else zoom /= 1-increment;

Ah, I think you have mistaken me for a computer programmer :-(.
I think it is important that the code is understandable, as well as works correctly. If you would like to re-write the code in a way understandable to others, I will put it in the repo.

> the significance of a negative "zoom" value,

Permissible ranges for the zoom parameter are >= +1 and <= -1, corresponding to the displayed zoom settings of X:1 and 1:X.
If you have a positive zoom value and reduce it to below 1 e.g 0.5, then you must invert and negate it - the resultant -2 is displayed as a zoom setting of 1:2

> won't let me shrink the thumbnails panel to get a single column,

The width of that entire panel is determined by the width of the menu bar. There is an extra item in the menu bar now, which causes this effect. But is a bit more complex than that, because the theme/font you are using affects the width of the menu bar also.

>  I prefer the current behavior where the "File" menu stays visible but "Help" gets obscured on the right

This appears to be a difference in behaviour between GTK2 and GTK3

> Tried configuring with --disable-gtk3 but got a bunch of errors

If you switch between GTK2 and GTK3 you should make a distclean. Try:
`sudo make uninstall; sudo make distclean; ./autogen.sh; make -j<x>`

**Comment by archenemies** [comment]
Thanks for the GTK2 instructions. Indeed I prefer that version. (I think you forgot a "./configure --disable-gtk3" after the "./autogen.sh" though)

I'm not sure how best to send a patch but this is what I put together:

[0001-Simplify-pr_zoom_adjust_real.txt](https://github.com/BestImageViewer/geeqie/files/1424014/0001-Simplify-pr_zoom_adjust_real.txt)

Hope it helps. I find it much easier to read. I tested it superficially.

**Comment by lachalunilim** [comment]
Hi :)
I'm sorry to exhume this issue, but I want to let you know that solving it is a regression for me.
(If it's not the right place to do so please let me know)
I've been using Geeqie on an old system for quite a long time and I just discover this new behavior of multiplicative increment on my updated system.
For me having the zoom increment being arithmetic was one of the *best* feature of geeqie: just like in most image editor (The GIMP, Krita, probably Photoshop) have some fixed zoom level (25%, 33%, 50%, 66%, 100%, 150%, 200%, ...), using arithmetric progression allowed to "snap" on whole or simple-fraction-al zoom level, improving filtering/interpolation. e.g. I use to set the step to 0.25, which let me reach {25%, 50%, ..., 100%, ..., 150%, ..., 200%, ..., 250%, ..., 300%, ...}.
With the new behavior it's impossible to have 100%, 200% and 300% when zooming:
with zoom inc = 1.00 I can only reach {25%, 50%, 100%, 200%, 400%, 800%, ...} (lacking 300%, 500%, ...)
with zoom inc = 0.41 (the closest to sqrt(2)-1): {..., 100%, 141%, 199%, 280%, 395%, ...} (none is ok)
with zoom inc = 0.1 (smaller step better?): {..., 100%, 110%, 121%, 133%, 146%, 161%, 177%, 195%, 214%) (not really better)
(The same applies in the downscaling direction)
While I can understand the reasoning of "0.1 increments make sense at 100%, but are ridiculous at 1000% or 20%", it was not that bad IMO, and at least was better that what we get now.
Not sure what the correct fix would be :/.
- Having a setting to choose between arithmetic and multiplicative increment (but I hate when I have this kind of request myself^^)
- Or having an explicit list of allowed zoom level (would be great!) but it's less user-friendly I guess?
Thank you for your help, and for this nonetheless awesome viewer :)

**Comment by caclark** [comment]
There are menu items for fixed zoom values  1:2, 1:3, 1:4, 4:1, 3:1, and 2:1
You can assign these to keystrokes or place icons on the toolbar.

If that is not sufficient, it is possible to have a user option to select geometric/arithmetic zoom, or maybe a modifier key (control or alt or shift) to change the zoom key mode of operation.

**Comment by lachalunilim** [comment]
Thanks for your response :)
> There are menu items for fixed zoom values 1:2, 1:3, 1:4, 4:1, 3:1, and 2:1

Ah? Indeed! I didn't know that.
That is a pertinent workaround, but it's not as smooth as simply scrolling with the mouse wheel, or hitting +/-; and it only provides me with a whooping new 1:3 and 3:1 zoom :grin: (as I can get the others naturally with the setting equal to 1.00)
I would greatly appreciate a setting, but **if I'm the only one to complain** it may not be worth it? I'm dev, so would it be reasonably easy to checkout the repo, reverse this change, and rebuild from source?
Or would it be so simple to add a setting or modifier key that you would put it to your backlog?^^

**Comment by caclark** [comment]
> Or would it be so simple to add a setting or modifier key that you would put it to your backlog?

The backlog is there because those are the ones I don't know how to fix :-(
This one I can fix - probably just a simple selection box in Preferences/Image. It may get done in a few days or so - or sooner if I find myself watching a Dolph Lundgren film.

**Comment by lachalunilim** [comment]
Ok, thank you so much :D Good luck!
